### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by tormento** [albertony/instructionsets#1]
Would you please provide a x86/x64 compiled build for Windows?

I can't really create on my own.

**Comment by albertony** [comment]
Hi.

Actually I did just 2 weeks ago:

https://github.com/albertony/instructionsets/releases/

**Comment by albertony** [comment]
I see that it did not appear in the right panel on the project front page, and it was because it was marked as a pre-release. I removed that label now, so it should be easier to find.
